export const STATUS_CODE_SUCCESS = 200;
export const STATUS_CODE_CREATED = 201;
export const STATUS_CODE_BAD_REQUEST = 400;
export const STATUS_CODE_UNAUTHENTICATED = 401;
export const STATUS_CODE_UNAUTHORIZED = 403;
export const STATUS_CODE_NOT_FOUND = 404;
export const STATUS_CODE_SERVER_ERROR = 500;
